<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>ANOVA in R</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="logo.svg" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R Modules</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="https://brownhr.github.io">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    R Modules
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RModule1.html">R Module 1</a>
    </li>
    <li>
      <a href="RModule2.html">R Module 2</a>
    </li>
    <li>
      <a href="RModule3.html">R Module 3</a>
    </li>
    <li>
      <a href="RModule4.html">R Module 4</a>
    </li>
    <li>
      <a href="RModule5.html">R Module 5</a>
    </li>
    <li>
      <a href="RModule6.html">R Module 6</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">ANOVA in R</h1>

</div>


<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('left', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<div id="what-is-anova" class="section level1">
<h1>What is <em>ANOVA</em>?</h1>
<p>Analysis of Variance (<em>ANOVA</em>) describes a set of statistical
models used to analyze the differences among means. A number of
functions exist in R (such as the aptly-named <code>anova()</code>) to
conduct an ANOVA, each with strengths and weaknesses. Doing an ANOVA in
R therefore involves more than just calling a single function. In this R
Module, we’ll review the basic steps of an ANOVA and demonstrate the
related tests you can use if your data doesn’t conform to the basic
assumptions of the test outlined below.</p>
<p>The basic form of ANOVA makes the following assumptions:</p>
<ol style="list-style-type: decimal">
<li>Observations within each sample are randomly selected and
independent from each other</li>
</ol>
<ul>
<li>In our case, this means they are not spatially autocorrelated,
something we’ll go in-depth into in a future R Module.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Sample observations are normally distributed</li>
<li>The variances of the samples are homogeneous</li>
</ol>
<p>We can test each of these assumptions statistically before proceeding
with ANOVA.</p>
<div id="importing-data" class="section level2">
<h2>Importing Data</h2>
<p>Before we get started talking about ANOVA in depth, let’s take a
moment to read in the data we need. When our data are stored in a
<code>.zip</code>, we need to extract the files. Of course, we could do
this manually, but R can do this too!</p>
<p>We can use the <code>unzip()</code> function, which takes two inputs,
<code>zipfile</code>, or the name of the file we want to unzip, and
<code>exdir</code>, the ‘output folder’. Reading the documentation for
this function, the <code>exdir</code> argument creates the folder if
necessary.</p>
<pre class="r"><code>unzip(
  zipfile = &quot;data/NC_REGION.zip&quot;,
  
  # The function choose.dir() allows us to interactively choose a folder;
  # similarly, the file.choose() function gives us an interactive window to
  # select a folder.
  exdir = choose.dir()
)</code></pre>
<p>If we now navigate to the folder we extracted our <code>.zip</code>
to, we’ll see a Shapefile called <code>NC_REGION.shp</code>. As always,
when working with Shapefiles, you need to have all the auxiliary files
nearby.</p>
</div>
<div id="testing-anova-assumptions" class="section level2">
<h2>Testing ANOVA Assumptions</h2>
<p>For the moment, let’s demonstrate ANOVA as if the data we have
conform to these assumptions. Like in previous labs, we’ll load
Shapefiles with the <code>sf</code> package.</p>
<pre class="r"><code>library(sf)

# Replace the argument inside `read_sf()` with the path to your Shapefile
NC &lt;- read_sf(&quot;data/NC_REGION/NC_REGION.shp&quot;)</code></pre>
<p>Let’s take a look at our data:</p>
<pre class="r"><code>View(NC)</code></pre>
<p>One thing we need to do is convert our <code>Region</code> column
from <code>character</code> to <code>factor</code>:</p>
<pre class="r"><code>NC$Region &lt;- as.factor(NC$Region)</code></pre>
<p>Then, looking at our <code>Region</code> column, we can see the
number of counties in each region. Because we have a different number of
observations (counties) in each region, our design is ‘unbalanced’:</p>
<pre class="r"><code>summary(NC$Region)</code></pre>
<pre><code>## Coastal Plain     Mountains      Piedmont 
##            41            23            36</code></pre>
<p>Let’s check out how the manufacturing jobs stored in the variable
<code>MNEM2000</code> interact with our new regional categorization by
creating a boxplot. Even though boxpots use median values to display
variation rather than mean values, they still show us the approximate
‘middle’ of each variable by region and their respective dispersion.</p>
<pre class="r"><code># We can use base R to make a simple boxplot

boxplot(MNEM2000 ~ Region, data = NC)</code></pre>
<p><img src="RModule6_files/figure-html/mnem-region-boxplot-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>The Piedmont region looks a bit more dispersed than the other two and
the median is shifted higher. Is it enough for us to detect a difference
using ANOVA? Let’s find out.</p>
<p>Because we have an unbalanced design, the base R ANOVA function isn’t
quite the best choice, but we’ll call it to see what it returns.</p>
<pre class="r"><code>anova &lt;- aov(MNEM2000 ~ Region, data = NC)

print(anova)</code></pre>
<pre><code>## Call:
##    aov(formula = MNEM2000 ~ Region, data = NC)
## 
## Terms:
##                     Region  Residuals
## Sum of Squares  1870914725 5528223748
## Deg. of Freedom          2         97
## 
## Residual standard error: 7549.304
## Estimated effects may be unbalanced</code></pre>
<pre class="r"><code>summary(anova)</code></pre>
<pre><code>##             Df    Sum Sq   Mean Sq F value   Pr(&gt;F)    
## Region       2 1.871e+09 935457362   16.41 7.25e-07 ***
## Residuals   97 5.528e+09  56991997                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Notice that the results first warn us about our unbalanced samples.
In both sets of results, we’re given some key information. The input for
the nominator in the ANOVA calculation is provided by
<code>Region</code>, and the denominator is provided in
<code>Residuals</code>. The calculated estimates of the variance between
the sample means (nominator) and within the samples themselves
(denominator) are provided the degrees of freedom needed to plot the
F-distribution. In our case, we’ll have an F distribution of <span
class="math inline">\((2,97)\)</span>. This distribution is used to
calculate the critical value of F at an alpha of <span
class="math inline">\(0.05\)</span>, the default for the test.</p>
<p>The calculated F-Statistic is <code>16.41</code>, which means the
numerator is about 16 times the denominator. This illustrates a big
difference between regions and the <span
class="math inline">\(p\)</span>-value for that F statistic is <span
class="math inline">\(7.25\times10^{-7}\)</span>, which is considerably
less than <span class="math inline">\(0.05\)</span>. Thus, at <span
class="math inline">\(\alpha = 0.05\)</span>, we can reject the null
hypothesis.</p>
</div>
<div id="one-way-test" class="section level2">
<h2>One-way Test</h2>
<p>Another version of ANOVA is called the One-way test of variance,
found in the <code>oneway.test()</code> function. This version tests
whether two or more samples from normal distributions have the same
means, but the variances are not necessarily assumed to be equal. Using
this function with the <code>var.equal = TRUE</code> argument, the
results should be identical to those from <code>aov()</code>:</p>
<pre class="r"><code>oneway.test(MNEM2000 ~ Region, data = NC, var.equal = TRUE)</code></pre>
<pre><code>## 
##  One-way analysis of means
## 
## data:  MNEM2000 and Region
## F = 16.414, num df = 2, denom df = 97, p-value = 7.246e-07</code></pre>
<p>Setting <code>var.equal = FALSE</code> leads to differing
results:</p>
<pre class="r"><code>oneway.test(MNEM2000 ~ Region, data = NC, var.equal = FALSE)</code></pre>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  MNEM2000 and Region
## F = 11.237, num df = 2.000, denom df = 46.631, p-value = 0.000104</code></pre>
<p>If we wish to test if our variances are homogeneous, we can use a
test called the Bartlett’s test of Homoscedasticity. This test examines
the null hypothesis that the variances in each of the set of samples are
the same. As the test statistic gets larger, we’re more likely to reject
the null hypothesis (i.e., as the statistic increases, the variances are
more likely to not be homogeneous).</p>
<pre class="r"><code>bartlett.test(MNEM2000 ~ Region, data = NC)</code></pre>
<pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  MNEM2000 by Region
## Bartlett&#39;s K-squared = 48.261, df = 2, p-value = 3.314e-11</code></pre>
<p>In this case, we should reject the null hypothesis, which mean we
need to run <code>oneway.test()</code> with
<code>va.equal = FALSE</code>.</p>
<pre class="r"><code>oneway.test(MNEM2000 ~ Region, data = NC, var.equal = FALSE)</code></pre>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  MNEM2000 and Region
## F = 11.237, num df = 2.000, denom df = 46.631, p-value = 0.000104</code></pre>
<p>By accommodating the differences in variances between the samples,
our calculation for the F-Statistic changes (note the smaller degrees of
freedom; 46.631 vs. 97). However, we can still reject the null
hypothesis at <span class="math inline">\(\alpha = 0.05\)</span>. This
suggests that manufacturing is different in at least one of the regions
of North Carolina.</p>
</div>
<div id="testing-normality" class="section level2">
<h2>Testing Normality</h2>
<p>There’s one last condition to consider that could be impacting our
results. ANOVA assumes that the sampled variable is normally
distributed; we can check this as well. First, let’s make a simple
density plot of <code>MNEM2000</code>. If it is approximately normal, we
should see a roughly symmetric curve.</p>
<pre class="r"><code>plot(
  density(x = NC$MNEM2000)
)</code></pre>
<p><img src="RModule6_files/figure-html/density-plot-1.png" width="672" style="display: block; margin: auto;" />
Our graph isn’t normal; note the positive skew. We can test the
assumption of normality statistically using the <em>Shapiro-Wilk
Normality Test</em>.</p>
<pre class="r"><code>shapiro.test(NC$MNEM2000)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  NC$MNEM2000
## W = 0.74296, p-value = 6.126e-12</code></pre>
<p>Because the <span class="math inline">\(p\)</span>-value is
statistically significant, we can reject the null hypothesis (our
distribution is not normal).</p>
</div>
<div id="normalizing-our-distribution" class="section level2">
<h2>Normalizing our Distribution</h2>
<p>Our variable is a long way from normal, but there are several methods
to use to normalize our data. Common transformations include square root
(<code>sqrt()</code>) and <span class="math inline">\(log_{}10\)</span>
(<code>log10()</code>). Let’s try a square root transformation to see if
it improves our results:</p>
<pre class="r"><code># We can use the `mutate()` function from `dplyr` to add and change columns
library(dplyr)
NC &lt;- NC %&gt;% 
  mutate(
    sqrt_MNEM2000 = sqrt(MNEM2000)
  )

plot(density(NC$sqrt_MNEM2000))</code></pre>
<p><img src="RModule6_files/figure-html/density-sqrt-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Let’s test it with Shapiro-Wilk:</p>
<pre class="r"><code>shapiro.test(NC$sqrt_MNEM2000)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  NC$sqrt_MNEM2000
## W = 0.92926, p-value = 4.521e-05</code></pre>
<p>We’re closer to normal, but not enough to fail to reject the <span
class="math inline">\(H_0\)</span> from the Shapiro-Wilk test. Still,
it’s better than before, so we should try our ANOVA again using the
transformed manufacturing variable:</p>
<pre class="r"><code>anova_sqrt &lt;- oneway.test(sqrt_MNEM2000 ~ Region, data = NC, var.equal = FALSE)
anova_sqrt</code></pre>
<pre><code>## 
##  One-way analysis of means (not assuming equal variances)
## 
## data:  sqrt_MNEM2000 and Region
## F = 16.822, num df = 2.000, denom df = 52.498, p-value = 2.263e-06</code></pre>
<p>Our test detects a stronger significant difference (i.e., lower <span
class="math inline">\(p\)</span>-value). The tests are more sensitive to
deviations from the assumption of normality than they are to the
assumption of homogeneity of variances. Since our data still isn’t very
normal, we may want to consider a nonparametric, “distribution-free”
version of the test. Fortunately, there are versions of ANOVA that don’t
require normally distributed data; we’ll use one called the
Kruskal-Wallis test. It produces different test statistics, but the
interpretation is very similar to <code>aov()</code> and
<code>oneway.test()</code>.</p>
<pre class="r"><code>kruskal.test(sqrt_MNEM2000 ~ Region, data = NC)</code></pre>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  sqrt_MNEM2000 by Region
## Kruskal-Wallis chi-squared = 27.64, df = 2, p-value = 9.954e-07</code></pre>
</div>
<div id="post-hoc-test" class="section level2">
<h2>Post-Hoc Test</h2>
<p>It appears that we’re finding a similar effect when we use either a
transformed variable or a nonparametric test. But which region (or
regions) account for the difference? We have one last test to perform,
called the Tukey Multiple Comparisons of the Means Test. This test
creates confidence intervals for the difference of sample means for each
pair of samples in turn. The <span class="math inline">\(H_0\)</span> is
that the confidence interval should contain 0, based on the assumption
that the samples are from the same population. A low <span
class="math inline">\(p\)</span>-value for the confidence interval means
that one of the two samples is different.</p>
<pre class="r"><code>aov &lt;- aov(sqrt_MNEM2000 ~ Region, data = NC)

tukey &lt;- TukeyHSD(aov)
tukey</code></pre>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = sqrt_MNEM2000 ~ Region, data = NC)
## 
## $Region
##                              diff       lwr      upr     p adj
## Mountains-Coastal Plain  3.921318 -18.54440 26.38703 0.9093413
## Piedmont-Coastal Plain  49.508376  29.81191 69.20484 0.0000001
## Piedmont-Mountains      45.587058  22.56750 68.60661 0.0000241</code></pre>
<p>The test <span class="math inline">\(p\)</span>-values are smallest
when the Piedmont region is considered(i.e., Piedmont/Coastal Plains and
Piedmont/Mountains). This suggests that the Piedmont is the region most
likely to be different than the others. A visual comparison of the
confidence intervals helps illustrate the point.</p>
<pre class="r"><code>plot(tukey)</code></pre>
<p><img src="RModule6_files/figure-html/tukey-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>If two regions are governed by the same probability distribution
(same population), we would expect differences of their respective
sample means to be close to 0. The Tukey test calculates pairwise
confidence intervals for each possible pair combination. If the
<em>CI</em>s don’t include zero,we have evidence that they are
different. The Piedmont-Mountains CI and Piedmont-Coastal Plain CI (not
labeled, but middle category on the plot) does not include 0 at all (it
also has the lowest p-values in the results). The Mountains-Coastal
Plain CI does include 0. The Piedmont region is different and the effect
identified by the ANOVA tests is because of this difference.</p>
<p>Are these results definitive enough for us to really reject the ANOVA
null hypothesis? I would agree that results are consistent about the
Piedmont region, and our ANOVA result would still remain significant if
we dropped our alpha from 0.05 to, say, 0.01. If this was not the case,
we could redraw the regions or perform different transformations of the
manufacturing counts to produce different or more definitive results.
This illustrates the sometimes iterative nature of statistics – the
findings of one process can lead us back to revisit early efforts that
require us to repeat our analysis again later.</p>
<hr />
<hr />
</div>
</div>
<div id="assignment" class="section level1">
<h1>Assignment</h1>
<p><strong>In an R Markdown (.Rmd, see R Module 4) Report, repeat the
steps above for either the <code>MNEM1990</code> or data of your own
(e.g., land cover, census)`. Your Report should include:</strong></p>
<ul>
<li>The R code used to generate your results and plots</li>
<li>Interpretation of each of these tests; i.e., what does the statistic
and <span class="math inline">\(p\)</span>-value represent?</li>
</ul>
<ol style="list-style-type: decimal">
<li>Boxplot of regions or categories</li>
</ol>
<ul>
<li>Add notches to your boxplots – Explain why notches are
important/what they add</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>ANOVA output</li>
</ol>
<ul>
<li>Report your F-Statistic and if you should reject or fail to reject
the <span class="math inline">\(H_0\)</span>.</li>
</ul>
<ol start="3" style="list-style-type: decimal">
<li>One-way Test with equal variances</li>
<li>Bartlett’s K-Squared</li>
<li>One-way Test with unequal variances</li>
<li>Shapiro-Wilk Normality Test</li>
</ol>
<ul>
<li>If the data are non-normal, transform variables accordingly and
re-run the test</li>
<li>Illustrate data using density plot for both un-transformed and
transformed data</li>
</ul>
<ol start="7" style="list-style-type: decimal">
<li>Tukey Multiple Comparisons of Mean Test</li>
</ol>
<ul>
<li>Describe which regions or categories are different</li>
<li>Include a plot of your confidence intervals</li>
</ul>
</div>

<p>&copy; 2022 brownhr & M. Sugg. v.0.0.8</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
