---
title: "Spatial Regression"
output:
  html_document:
      toc: true
      toc_float: true
      toc_collapsed: true
      toc_depth: 3
      number_sections: false
---

***

# Spatial Regression in R

Regression residuals are the primary way to assess if a regression violates any assumptions of the general linear model. Although all the assumptions are important, the violation of the assumption of independence is common with spatially organized data. This has led to the development of a family of alternate regression models that can accommodate spatial dependence. We'll work with two of theme models continuing from the previous two R Modules. These are known as the *spatial lag model* and *spatial error model*. Both models account for spatial dependence by including new parameters that must be estimated; each model, however, handles this in a different way...

## Spatial Lag Model

The spatial lag model, shown below, introduces a new explanatory variable and an associated coefficient that must be estimated:

$$ y = \rho W_y + \beta X + \varepsilon$$

The new variable, $W_y$, is the "lag variable" and represents, for each spatial unit, the weighted average of the values of the observations among its neighbors (when working with a row-standardized matrix). 

The term $\beta X$ represents our independent variables, and epsilon ($\varepsilon$) is our "error term", which describes the amount by which an observed value differs from the expected value, based on the whole population.

Just like in "normal" regression models, there exists a correlation coefficient, in this case rho ($\rho$), and for spatial regression the value of $\rho$ must be estimated. $\rho$ is one of the key statistics; our null hypothesis is that $\rho = 0$, which represents zero spatial dependence in the $W_y$ dependent variable.

A statistically significant result, therefore is when $\rho \neq 0$, meaning we have successfully adjusted our model to account for any spatial dependence. 

As with Moran's I, $\rho$ can be either positive, indicating positive spatial dependence, or negative, indicating negative spatial dependence. 


## Spatial Error Model


$$y = \beta X + \varepsilon; \;\varepsilon = \lambda W \varepsilon + \xi$$

