<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Probability and Confidence Intervals</title>

<script src="site_libs/header-attrs-2.14/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="aoa_r.svg" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R Modules</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="Syllabus.html">
    <span class="fa fa-file-text"></span>
     
    Syllabus
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    R Modules
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="RModule1.html">R Module 1</a>
    </li>
    <li>
      <a href="RModule2.html">R Module 2</a>
    </li>
    <li>
      <a href="RModule3.html">R Module 3</a>
    </li>
    <li>
      <a href="RModule4.html">R Module 4</a>
    </li>
    <li>
      <a href="RModule5.html">R Module 5</a>
    </li>
    <li>
      <a href="RModule6.html">R Module 6</a>
    </li>
    <li>
      <a href="RModule7.html">R Module 7</a>
    </li>
    <li>
      <a href="RModule8.html">R Module 8</a>
    </li>
    <li>
      <a href="RModule9.html">R Module 9</a>
    </li>
    <li>
      <a href="RModule10.html">R Module 10</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Probability and Confidence Intervals</h1>

</div>


<hr />
<div id="calculating-probability-of-a-normal-distribution"
class="section level1">
<h1>Calculating Probability of a Normal Distribution</h1>
<p>For this R module, we’ll use <code>R</code> to simplify a somewhat
complicated task – creating confidence intervals around a point estimate
of population parameters. For all the examples below, we’ll keep things
simple by assuming that the population parameters we’re interested in is
the population mean, and that the best (i.e., least biased and most
efficient) point estimator of that parameter is the sample mean.</p>
<p>Before we get started, let’s revisit the properties of the normal
distribution: a symmetrical distribution around an expected value mean
and a standard deviation. We can generate an example of this
distribution in <code>R</code>:</p>
<pre class="r"><code># This code generates 200 equally-spaced values between -4 and 4, which we&#39;ll
# use as the &#39;input values&#39;

input &lt;- seq(from = -4,
         to = 4,
         length = 200)</code></pre>
<p>Next, we’ll calculate the normal probability density of
<code>input</code> using <code>dnorm()</code>. This calculates the
likelihood that each value of <code>input</code> will be observed, and
assigns it to the variable <code>output</code>. Note that we must
specify the mean and standard deviation; we’ll set them to 0 and 1,
respectively.</p>
<pre class="r"><code>output &lt;- dnorm(x = input,
           mean = 0,
           sd = 1)</code></pre>
<p>We can plot these to see the classic “bell-shaped” curve.</p>
<p>For normally distributed data, we can estimate the probability of
observing a range of values by calculating the area under the curve that
corresponds to those values. For example, consider the area under the
curve below. What is the probability that any value of x will be <span
class="math inline">\(\leq\)</span> 0?</p>
<p><img src="RModule5_files/figure-html/area1-1.png" width="85%" style="display: block; margin: auto;" /></p>
<p>It should be 50% because the curve is symmetric, right? We can test
this in <code>R</code> with <code>pnorm()</code>, which calculates the
probability of a value occurring to the left of the input
<code>q</code>:</p>
<pre class="r"><code>pnorm(q = 0,
      mean = 0,
      sd = 1)</code></pre>
<pre><code>## [1] 0.5</code></pre>
<p>Or, 50%.</p>
<p>We could substitute a value for <code>q</code>, and
<code>pnorm()</code> would calculate the probability of that value (if
you want, the “area under the curve” to the left of that value).</p>
<p>But what if we want the probability for a specific range such as from
-1 to +1 such as the figure below?</p>
<p><img src="RModule5_files/figure-html/area2-1.png" width="85%" style="display: block; margin: auto;" /></p>
<p>All we’d need to do is subtract the probability of the value on the
right by the probability of the value on the left:</p>
<p><img src="RModule5_files/figure-html/area3-1.png" width="85%" style="display: block; margin: auto;" /></p>
<pre class="r"><code>p_1 &lt;- pnorm(1, mean = 0, sd = 1)

p_2 &lt;- pnorm(-1, mean = 0, sd = 1)


p_1 - p_2</code></pre>
<pre><code>## [1] 0.6826895</code></pre>
<p>We can interpret this as meaning there being a 68.27% probability of
a single observed value of <code>input</code> as falling between -1 and
+1.</p>
<div id="questions" class="section level2">
<h2>Questions</h2>
<ol style="list-style-type: decimal">
<li>Adapt the code above to calculate the area under the curve
(probability) for the following intervals of <code>input</code>:
<ul>
<li>(-2, 2)</li>
<li>(-3, 3)</li>
<li>(-4, 4)</li>
</ul></li>
</ol>
<hr />
</div>
</div>
<div id="qnorm" class="section level1">
<h1><code>qnorm()</code></h1>
<p>What if we know the probabilities we want to achieve, but don’t know
the values of <code>input</code> associated with these probabilities?
Consider the figure below; 95% of the area of the curve lies to the left
of what value of <code>input</code>?</p>
<p><img src="RModule5_files/figure-html/qnorm1-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>We can use <code>qnorm()</code>, which is the “inverse” of
<code>pnorm()</code>; <code>qnorm()</code> returns the value of
<code>input</code> to the left of a probability <code>p</code> (the area
under the curve, visually speaking).</p>
<pre class="r"><code>qnorm(p = 0.95,
      mean = 0,
      sd = 1)</code></pre>
<pre><code>## [1] 1.644854</code></pre>
<p>We can interpret this as meaning there is a 95% probability of a
single observed value of <code>input</code> as falling between -4 and
1.644854 (note, these values of <code>input</code> are also z-scores,
since our mean is 0 and our standard deviation is 1). Because the area
under the curve must sum to 1, we can also say that the probability of
observing a value <code>input</code> that is more than 1.644854 is 5%
(100% - 95%).</p>
<div id="questions-1" class="section level2">
<h2>Questions</h2>
<ol start="2" style="list-style-type: decimal">
<li>Use <code>qnorm()</code> to calculate the values of
<code>input</code> for each of the following circumstances. Provide both
the calculated values of <code>input</code> and your R code.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>20% of the area of the curve is to the left of an unknown value of
x</li>
<li>67% of the area of the curve is to the right of an unknown value of
x</li>
</ol>
<hr />
<hr />
</div>
</div>
<div id="confidence-intervals" class="section level1">
<h1>Confidence Intervals</h1>
<p>Understanding the normal distribution is important to understanding
confidence intervals. Why? Recall that we can usually assume that our
sampling distribution of a variable is normal even if the actual
population distribution isn’t normal. If the underlying probability
function that governs the sampling process is normal, we can use the
logic described above to assess how likely a range around a given sample
mean – which is a point estimate of our population – will actually
contain the true population mean.</p>
<p>Suppose we’ve collected a random sample of 10 recent graduates and
asked what their annual salary is. We can enter our results in R by
creating a vector:</p>
<pre class="r"><code>x &lt;- c(44617, 7066, 17594, 2726, 1178, 18898, 5033, 37151, 4514, 4000)</code></pre>
<p>Our goal is to use our sample to create an estimate of the population
mean (i.e., the average salary of all recent graduates), and create a
measure of how confident we are that the population mean is within a
particular interval around our estimate. Put another way, we need to
create a point estimate of the population from our sample and then
create confidence intervals using that estimate.</p>
<p>In addition to our sample values, we are told that the standard
deviation for salary among our population is $15,000, but that the
population mean salary is unknown. For the sake of argument, let’s
assume the population distribution is approximately normal. Let’s save
this as <code>sdev</code>:</p>
<pre class="r"><code>sdev &lt;- 15000</code></pre>
<p>With this information, let’s calculate a 70% confidence interval
around our sample mean. This means that we want to find two currently
unknown values for our sample mean (<span
class="math inline">\(\bar{X}\)</span>, or “X-bar”). 70 time out of 100
samples, we expect the actual population mean to fall in between these
two values. In other words, we’re interested in finding the values of
<span class="math inline">\(x\)</span> that correspond to this area
under the normal curve:</p>
<p><img src="RModule5_files/figure-html/ci-1.png" width="70%" style="display: block; margin: auto;" /></p>
<div id="finding-cis-in-r" class="section level2">
<h2>Finding <em>CI</em>s in R</h2>
<p>Let’s approach this with a bit of <code>R</code> programming. Suppose
we have a set of data and want to regularly find a confidence interval
of a given size (e.g., 70% or 95%). The formula for a confidence
interval under these assumptions is: <span class="math display">\[
\bar{X} = \pm z\frac{\alpha}{2}\frac{\sigma}{\sqrt{n}}\]</span> If we
want a confidence interval (<em>CI</em>) of 70%, our alpha needs to be
0.3 (<em>CI</em> = <span class="math inline">\(1 - \alpha\)</span>).
<span class="math inline">\(\alpha\)</span> then refers to the areas
both to the left and to the right of our unknown <span
class="math inline">\(\bar{X}\)</span> values (or the area “outside” our
shaded region). Since the total area we’re interested in is 30%, we need
to divide <span class="math inline">\(\alpha\)</span> by two. In other
words, we need the z-scores for <span class="math inline">\(x &lt;
15\%\)</span> and <span class="math inline">\(x &gt; 85\%\)</span>.
Remember, we can use <code>qnorm()</code> for this:</p>
<pre class="r"><code>z.alpha.2 &lt;- qnorm(p = 0.85,
                  mean= 0,
                  sd = 1)</code></pre>
<p>We can also easily calculate the mean:</p>
<pre class="r"><code>xbar &lt;- mean(x)
xbar</code></pre>
<pre><code>## [1] 14277.7</code></pre>
<p>So, we know the z-scores for our interval and the sample mean, <span
class="math inline">\(\bar{X}\)</span>. Since we also know the standard
deviation <span class="math inline">\(\sigma\)</span>, we can simply
plug these into our formula to provide our answer in real units of x (in
this case, dollars).</p>
<pre class="r"><code>lbound &lt;- xbar - (z.alpha.2 * (sdev / sqrt(10)))
ubound &lt;- xbar + (z.alpha.2 * (sdev / sqrt(10)))

lbound</code></pre>
<pre><code>## [1] 9361.465</code></pre>
<pre class="r"><code>ubound</code></pre>
<pre><code>## [1] 19193.94</code></pre>
<p>What does this mean? We are 70% confident that the actual
(population) mean salary of all recent graduates lies within the range
between $9361.46 and $19193.94</p>
<div id="writing-a-function-in-r" class="section level3">
<h3>Writing a function in R</h3>
<p>Let’s take everything we’ve done so far and compose an R function.
Rather than running everything line-by-line, we can call this function
with the arguments we set, which makes this a lot more repeatable,
reproducible, and reduces our chance of errors.</p>
<p>To create a function in R, we use the form:</p>
<pre><code>function_name &lt;- function(arg1, arg2, etc.) {
  contents of our function...
}</code></pre>
<p>We can call this function by first, defining the function in our
environment by hitting <code>Ctrl-Enter</code> within an R script, and
second, using the function just like any other R function.</p>
<p>Let’s try it out! We’ll call our function <code>confidence.</code> We
need a couple arguments (inputs, options, etc.), including: our data,
<code>input</code>, our population standard deviation (15,000), and our
desired confidence interval (70%, or 0.7)</p>
<pre class="r"><code>confidence &lt;- function(x, sdev = 15000, ci) {
  # Notice that we&#39;ve set the sdev argument to 15000, which means we&#39;ve given
  # the function a default argument. We don&#39;t need to specify sdev whenever we
  # call the function, but if we do, it&#39;ll overwrite our default argument.
  
  # The length function gives us the number of elements, or n in our equation for CIs
  n &lt;- length(x)
  xbar &lt;- mean(x)
  alpha &lt;- (1 - ci) / 2
  z.alpha.2 &lt;- qnorm(p = 1 - alpha,
                     mean = 0,
                     sd = 1)
  lbound &lt;-
    xbar - (z.alpha.2 * (sdev / sqrt(n)))
  ubound &lt;-
    xbar + (z.alpha.2 * (sdev / sqrt(n)))
  
  
  # Let&#39;s round to 2 decimals, so we have dollars and cents
  lbound &lt;- round(lbound, digits = 2)
  ubound &lt;- round(ubound, digits = 2)
  
  return(c(lbound, ubound))
}</code></pre>
<p>Let’s try our new function!</p>
<pre class="r"><code>confidence(x = x,
           sdev = 15000,
           ci = 0.7)</code></pre>
<pre><code>## [1]  9361.46 19193.94</code></pre>
<p>Neat!</p>
<p>Writing functions is <strong>by far</strong> the best thing to do to
perform tasks efficiently. Imagine you needed to calculate confidence
intervals for hundreds of datasets; by writing functions and doing
things in scripts, you can automate the entire process!</p>
<hr />
<hr />
</div>
</div>
</div>
<div id="assignment" class="section level1">
<h1>Assignment</h1>
<p>In addition to the questions above, answer the following in your lab
report:</p>
<ol start="3" style="list-style-type: decimal">
<li>Use the salary data from above to create 90%, 95%, and 99%
confidence intervals. Provide each interval, along with your code. What
happens to the interval range as you increase the confidence
percentage?</li>
</ol>
</div>

<p>&copy; 2022 Maggie Sugg & Harrison Brown. v.1.0.1</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
